# Generated by Django 5.2.8 on 2025-11-19 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
try:
    # Python 3.14+
    from uuid import uuid6
except ImportError:
    from uuid6 import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.CharField(db_index=True, max_length=50, verbose_name='ID')),
                ('_rowid', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retires_at', models.DateTimeField(blank=True, null=True)),
                ('short_name', models.CharField(max_length=200)),
                ('legal_html', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid6, primary_key=True, serialize=False, verbose_name='ID')), # FIXME: this should have serialize=True
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_sha256', models.BinaryField(max_length=32)),
                ('subject', models.CharField(max_length=150)),
                ('created_in_timezone', models.CharField(default=django.utils.timezone.get_current_timezone_name, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('_rowid', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('policy_set', models.ManyToManyField(to='policies.policy')),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField()),
                ('client_acceptance', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='policies.signature')),
                ('issuer_acceptance', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='policies.signature')),
                ('is_endorsement_on', models.ForeignKey(blank=True, limit_choices_to={'is_endorsement_on': None}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='endorsement_set', to='policies.contract')),
            ],
        ),
    ]
