# Generated by Django 5.2.8 on 2025-11-19 20:00

from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def main(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Contract = apps.get_model('policies', 'Contract')

    agents_group = Group.objects.create(
        name="Insurance Agents",
    )

    can_agree = Permission.objects.create(
        name="Can sign contract (as insurer)",
        codename="agent_for_contract",
        content_type=ContentType.objects.get_for_model(Contract),
    )

    agents_group.permissions.set([can_agree])


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('policies', '0001_initial'),
        ('auth', '0010_alter_group_name_max_length')
    ]

    operations = [
        migrations.RunPython(main),
    ]
